"""initial migration

Revision ID: e254036e3251
Revises: d423d793e2a0
Create Date: 2017-06-16 15:45:42.838048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e254036e3251'
down_revision = 'd423d793e2a0'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cls', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('paths', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'paths')
    op.drop_column('posts', 'cls')
    ### end Alembic commands ###
